import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(help_text='Custom name for this Certificate Management Protocol', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('acme', 'ACME'), ('scep', 'SCEP')], default='acme', max_length=20, verbose_name='Service type')),
                ('acme_directory_url', models.URLField(blank=True, help_text='e.g. https://acme-v02.api.letsencrypt.org/directory', verbose_name='Directory URL')),
                ('acme_challenge_type', models.CharField(blank=True, choices=[('http-01', 'HTTP-01'), ('dns-01', 'DNS-01'), ('tls-alpn-01', 'TLS-ALPN-01')], max_length=20)),
                ('acme_account_key_ref', models.CharField(blank=True, help_text='Vault URL for key', max_length=500, verbose_name='Account key reference')),
                ('acme_dns_provider', models.CharField(blank=True, help_text='e.g. rfc2136, cloudflare', max_length=100, verbose_name='DNS provider plugin')),
                ('acme_dns_credential_ref', models.CharField(blank=True, max_length=500, verbose_name='DNS credential reference')),
                ('acme_eab_kid', models.CharField(blank=True, max_length=200, verbose_name='EAB Key Identifier')),
                ('acme_eab_hmac_ref', models.CharField(blank=True, max_length=500, verbose_name='EAB HMAC key reference')),
                ('acme_account_url', models.URLField(blank=True, help_text='Populated after registration', verbose_name='Account URL (kid)')),
                ('acme_contact_email', models.CharField(blank=True, max_length=254, verbose_name='Contact e-mail')),
                ('acme_tos_agreed', models.BooleanField(default=False, verbose_name='Terms of service accepted')),
                ('acme_tos_agreed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terms accepted at')),
                ('acme_eab_required', models.BooleanField(default=False, verbose_name='External Account Binding required')),
                ('acme_preferred_chain', models.CharField(blank=True, max_length=200, verbose_name='Preferred issuer chain')),
                ('acme_profile', models.CharField(blank=True, max_length=100, verbose_name='Certificate profile')),
                ('scep_url', models.URLField(blank=True, verbose_name='SCEP endpoint URL')),
                ('scep_ca_fingerprint', models.CharField(blank=True, max_length=200, verbose_name='CA certificate fingerprint (SHA-256)')),
                ('scep_challenge_secret_ref', models.CharField(blank=True, max_length=500, verbose_name='Challenge password reference')),
                ('scep_encryption_algorithm', models.CharField(blank=True, choices=[('aes256', 'AES-256'), ('aes128', 'AES-128'), ('des3', '3DES')], max_length=20)),
                ('scep_digest_algorithm', models.CharField(blank=True, choices=[('sha256', 'SHA-256'), ('sha384', 'SHA-384'), ('sha512', 'SHA-512'), ('sha1', 'SHA-1')], max_length=20)),
                ('scep_renewal_mode', models.CharField(blank=True, choices=[('renewal', 'Renewal'), ('reenrollment', 'Re-enrollment')], max_length=20)),
                ('scep_ca_identifier', models.CharField(blank=True, help_text='For GetCACert?message=<id>', max_length=200, verbose_name='CA identifier')),
                ('scep_capabilities', models.JSONField(blank=True, null=True, verbose_name='Cached GetCACaps response')),
                ('scep_poll_interval', models.PositiveIntegerField(blank=True, help_text='Manual-approval CAs', null=True, verbose_name='Poll interval (s)')),
                ('scep_max_poll_attempts', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max poll attempts')),
                ('scep_ra_cert_ref', models.CharField(blank=True, max_length=500, verbose_name='RA certificate reference')),
                ('environment', models.CharField(blank=True, choices=[('production', 'Production'), ('staging', 'Staging'), ('lab', 'Lab')], max_length=20)),
                ('tls_trust_anchor', models.CharField(blank=True, max_length=500, verbose_name='Transport TLS trust anchor')),
                ('tls_verify', models.BooleanField(default=True, verbose_name='Verify server TLS certificate')),
                ('http_proxy', models.CharField(blank=True, max_length=200, verbose_name='HTTP proxy')),
                ('timeout_seconds', models.PositiveIntegerField(default=30, verbose_name='Request timeout')),
                ('retry_count', models.PositiveIntegerField(default=3, verbose_name='Retry attempts')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Protocol',
                'verbose_name_plural': 'Protocols',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(help_text='Name of the entity or team requesting this certificate (e.g. Firewall Team or Security team)', max_length=200, unique=True, verbose_name='Requestor name')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('contact', models.ManyToManyField(blank=True, related_name='pki_requestors', to='tenancy.contact', verbose_name='Contact users')),
                ('contact_group', models.ManyToManyField(blank=True, related_name='pki_requestors', to='tenancy.contactgroup', verbose_name='Contact user groups')),
                ('tags', taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Requestor',
                'verbose_name_plural': 'Requestors',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200, verbose_name='CA Name')),
                ('status', models.CharField(choices=[('automatic-requested', 'Automatic - Requested'), ('automatic-csr', 'Automatic - CSR'), ('automatic-created', 'Automatic - Created'), ('manual', 'Manual')], default='manual', max_length=30, verbose_name='Certificate Status')),
                ('expiration', models.CharField(blank=True, choices=[('1_month', '1 month'), ('45_days', '45 days'), ('2_months', '2 months'), ('3_months', '3 months'), ('200_days', '200 days'), ('1_year', '1 year'), ('2_years', '2 years'), ('3_years', '3 years'), ('4_years', '4 years'), ('5_years', '5 years'), ('6_years', '6 years'), ('7_years', '7 years'), ('8_years', '8 years'), ('9_years', '9 years'), ('10_years', '10 years'), ('15_years', '15 years'), ('20_years', '20 years')], help_text="If a parent CA is chosen, expiration cannot be later than the parent CA's expiration", max_length=20, verbose_name='CA Expiration time')),
                ('created_date', models.DateField(blank=True, help_text='Defaults to the current date', null=True, verbose_name='Certificate creation date')),
                ('expiration_date', models.DateField(blank=True, help_text='Defaults to created date + expiration time', null=True, verbose_name='Certificate expiration date')),
                ('certificate', models.TextField(blank=True)),
                ('private_key', models.CharField(blank=True, max_length=500, verbose_name='Vault URL to Private Key')),
                ('cn', models.CharField(blank=True, help_text='Unique Common Name', max_length=255, null=True, unique=True, verbose_name='CN')),
                ('csr', models.TextField(blank=True, help_text='Only allowed when a parent CA is chosen', verbose_name='Certificate Signing Request')),
                ('default_cert_expiration', models.CharField(blank=True, choices=[('1_month', '1 month'), ('45_days', '45 days'), ('80_days', '80 days'), ('2_months', '2 months'), ('3_months', '3 months'), ('200_days', '200 days'), ('1_year', '1 year'), ('2_years', '2 years'), ('3_years', '3 years')], max_length=20, verbose_name='Default Certificate Expiration time')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('parent_ca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_cas', to='netbox_pki.certificateauthority', verbose_name='Parent Certificate Authority')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificate_authorities', to='netbox_pki.protocol', verbose_name='Certificate Management Protocol')),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_authorities', to='netbox_pki.requestor', verbose_name='Requesting entity/department/team')),
                ('tags', taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Certificate Authority',
                'verbose_name_plural': 'Certificate Authorities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, blank=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cn', models.CharField(help_text='Unique Common Name', max_length=255, unique=True, verbose_name='CN')),
                ('expiration', models.CharField(choices=[('1_month', '1 month'), ('45_days', '45 days'), ('80_days', '80 days'), ('2_months', '2 months'), ('3_months', '3 months'), ('200_days', '200 days'), ('1_year', '1 year'), ('2_years', '2 years'), ('3_years', '3 years'), ('automatic', 'Automatic')], default='automatic', help_text='If Automatic, the expiration is taken from the chosen CA', max_length=20, verbose_name='Expiration time')),
                ('status', models.CharField(choices=[('automatic-requested', 'Automatic - Requested'), ('automatic-csr', 'Automatic - CSR'), ('automatic-created', 'Automatic - Created'), ('manual', 'Manual')], default='manual', max_length=30, verbose_name='Certificate Status')),
                ('certificate', models.TextField()),
                ('private_key', models.CharField(max_length=500, verbose_name='Vault URL to Private Key')),
                ('created_date', models.DateField(blank=True, help_text='Defaults to the current date', null=True, verbose_name='Certificate Creation Date')),
                ('expiration_date', models.DateField(blank=True, help_text='Defaults to created date + expiration time', null=True, verbose_name='Certificate Expiration Date')),
                ('alt', models.CharField(blank=True, help_text='One or more names separated by commas (e.g. alt1, alt2)', max_length=2000, verbose_name='Alternative Names')),
                ('csr', models.TextField(blank=True, verbose_name='Certificate Signing Request')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='netbox_pki.certificateauthority', verbose_name='Certificate Authority')),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='netbox_pki.requestor', verbose_name='Requesting entity/department/team')),
                ('tags', taggit.managers.TaggableManager(blank=True, through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ('cn',),
            },
        ),
    ]
